fullybooked_project/fullybooked/urls.py
from django.urls import path
from fullybooked import views

# the below code imports the relevant django machinery for url mapping, and
# the views module from "fullybooked" app.
# This allows the function "url" to be called and point to the index view for mapping in "urlpatterns"
app_name = 'fullybooked'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_book/', views.add_book, name='add_book'),
    path('review_book/', views.review_book, name='review_book'),
]

fullybooked_project/fullybooked_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from fullybooked import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'books', views.BookViewSet)

urlpatterns = [
    path('', views.index, name='index'),
    path('', include(router.urls)),
    path('fullybooked/', include('fullybooked.urls')),
    # The above maps any urls starting with fullybooked/ to be handled by the app
    # This makes the code more modular and reusable
    path('admin/', admin.site.urls),
]

fullybooked_project/fullybooked/models.py
from django.db import models


# A model is the Python object which describes the database table's data. The list of fields need specified here,
# along with the associated types or parameters. By default all models have an auto-increment integer field called id
# which is automatically assigned and acts a primary key.

# might not need separate models for new book and review? Maybe one book model, but two different forms which use the
# same model?


class Book(models.Model):
    title = models.CharField(max_length=150)
    author = models.CharField(max_length=80)
    rating = models.IntegerField(default=0)

    # Below is the Python equivalent of a toString() method.
    def __str__(self):
        return self.title


# class ReviewBook(models.Model):
#     rating = models.IntegerField(default=0)
#
#     def __str__(self):
#         return self.rating

fullybooked_project/fullybooked/forms.py
from django import forms
from fullybooked.models import Book


class NewBookForm(forms.ModelForm):
    title = forms.CharField(max_length=150, help_text="Please enter the book title.")
    author = forms.CharField(max_length=80, help_text="Please enter the author name.")
    rating = forms.IntegerField(initial=0)

    class Meta:
        model = Book
        fields = ('title', 'author')


# for use if the New Book form was seperate, but for now, adding a book to the shelf assumes tou have read it
class ReviewBookForm(forms.ModelForm):
    rating = forms.IntegerField(initial=0)

    class Meta:
        model = Book
        fields = ('rating',)


# for use if logging in
class LoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(widget=forms.PasswordInput())

fullybooked_project/fullybooked/views.py
from django.shortcuts import render, redirect
from fullybooked.models import Book
from fullybooked.forms import NewBookForm, ReviewBookForm
from fullybooked.serializers import BookSerializer
from rest_framework import viewsets


# Create your views here.

# responsible for the main page
def index(request):
    # querey the database for a list of all books stored.
    # Ordered by author alphabetically?
    book_list = Book.objects.order_by('author')

    # place the book_list in the context_dict dictionary to be passed to the template engine
    context_dict = {'books': book_list}

    return render(request, 'fullybooked/index.html', context=context_dict)


# creating a view for use with the New Book Form to add a book to your shelf
def add_book(request):
    form = NewBookForm()

    if request.method == 'POST':
        form = NewBookForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect('/fullybooked/')
        else:
            # if the form has errors
            print(form.errors)

    return render(request, 'fullybooked/add_book.html', {'form': form})


# creating a view for use with the Review Book Form, to rate a book
def review_book(request):
    form = ReviewBookForm()

    if request.method == 'POST':
        form = ReviewBookForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect('/fullybooked/')
        else:
            # if the form has errors
            print(form.errors)

    return render(request, 'fullybooked/review_book.html', {'form': form})


class BookViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all()
    serializer_class = BookSerializer

fullybooked_project/templates/fullybooked/add_book.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">

        <title>New Book</title>
        <link rel="stylesheet" type="text/css" href="static/css/bookshelf.css">
        <script src = "http://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


        <script>

      //  $(document).ready(function() {
      //    $.getJSON("http://localhost:8000/books", function(dataArray) {

      //    })
      //  })

        </script>

    </head>
        <body>
            <h1> Add a new book to your Fully Booked bookshelf!</h1>
            <div class="text">
                <form id = "newbook_form" method = "post" action = "{% url 'fullybooked:add_book' %}" enctype="multipart/form-data">
                    {{ form.as_p }}
                    {% csrf_token %}
                    <input type = "submit" name = "submit" value = "Add Book" />
                </form>
            </div>

        </body>
</html>

fullybooked_project/templates/fullybooked/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <div class="header">
        <title>Fully Booked</title>
    </div>
    <link rel="stylesheet" type="text/css" href="static/css/bookshelf.css">
    <script src = "http://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


    <script>

           $(document).ready(function() {
             $.getJSON("http://localhost:8000/books", function(dataArray) {
            //   $(dataArray).each(function(key, value){
            //             console.log(value);
                    //     jsonArray.push(dataArray);


                          const divArray = [];
                          var parentDiv = document.getElementById('bookshelf');

                          Object.keys(dataArray).forEach(function(entry){
                            console.log(dataArray[entry]);
                            console.log(dataArray[entry][2]);
                            console.log(dataArray[entry][2].attributes.title);

                            dataArray[entry].forEach(function(book) {
                              var newDiv = document.createElement('div');
                              // give value
                              newDiv.innerHTML = ("<h2>" + book.attributes.title + " " + "</h2>" + "<h3>" + "Rating: " + book.attributes.rating + " /5" + "</h3>");
                              newDiv.id = "book" + book.id;

                              if(book.id %4 == 0){
                                newDiv.classList.add("book", "book-yellow");
                              }else if(book.id %3 == 0){
                                  newDiv.classList.add("book", "book-blue");
                                }else{
                                newDiv.classList.add("book", "book-green");
                              }
                              divArray.push(newDiv);
                            })
                          })

                          divArray.forEach(function(index) {
                            parentDiv.appendChild(index);
                          })
                      })
                    })

    </script>


</head>



<body>
    <h1>Fully Booked</h1>
    <div class="text">
        Your bookshelf...</br>
    </div>
    <div class="text">
        <a href="{% url 'fullybooked:add_book' %}">Add a new book to your shelf</a></br>
                            {% csrf_token %}

    </div>

    <div class="bookshelf" id="bookshelf">

</body>
</html>

fullybooked_project/templates/fullybooked/review_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>